const API_URL = 'https://22.javascript.pages.academy/kekstagram';

const VISIBLE_COMMENTS_COUNT = 5;
const RENDER_DELAY = 500;
const RANDOM_PICTURE_COUNT = 10;
const ALERT_TIMER = 3000;

const RE_HASHTAG = /^#[A-Za-zа-яА-Я0-9]+$/;
const MAX_HASHTAG_LENGTH = 20;
const MIN_HASHTAG_LENGTH = 2;
const MAX_HASHTAG_AMOUNT = 5;
const MAX_COMMENT_LENGTH = 140;

const SCALE_STEP = 25;
const MIN_SCALE = 25;
const MAX_SCALE = 100;
const DEFAULT_SCALE = 100;
const FILE_TYPES = ['jpg', 'jpeg', 'png', 'gif'];

const GRAYSCALE_MIN = 0;
const GRAYSCALE_MAX = 1;
const GRAYSCALE_STEP = 0.1;
const SEPIA_MIN = 0;
const SEPIA_MAX = 1;
const SEPIA_STEP = 0.1;
const INVERT_MIN = 0;
const INVERT_MAX = 100;
const INVERT_STEP = 1;
const BLUR_MIN = 0;
const BLUR_MAX = 3;
const BLUR_STEP = 0.1;
const BRIGHTNESS_MIN = 1;
const BRIGHTNESS_MAX = 3;
const BRIGHTNESS_STEP = 0.1;
const DEFAULT_MIN = 0;
const DEFAULT__MAX = 1;
const DEFAULT__STEP = 1;

export {
  API_URL,
  VISIBLE_COMMENTS_COUNT,
  RENDER_DELAY,
  RANDOM_PICTURE_COUNT,
  RE_HASHTAG,
  MAX_COMMENT_LENGTH,
  MAX_HASHTAG_AMOUNT,
  MAX_HASHTAG_LENGTH,
  MIN_HASHTAG_LENGTH,
  ALERT_TIMER,
  GRAYSCALE_MAX,
  GRAYSCALE_MIN,
  GRAYSCALE_STEP,
  SEPIA_MAX,
  SEPIA_MIN,
  SEPIA_STEP,
  DEFAULT__STEP,
  DEFAULT__MAX,
  DEFAULT_MIN,
  BLUR_MAX,
  BLUR_MIN,
  BLUR_STEP,
  BRIGHTNESS_MAX,
  BRIGHTNESS_MIN,
  BRIGHTNESS_STEP,
  INVERT_MAX,
  INVERT_MIN,
  INVERT_STEP,
  MAX_SCALE,
  MIN_SCALE,
  FILE_TYPES,
  DEFAULT_SCALE,
  SCALE_STEP
}
